schema:
  companies[]:
    permId: "string"
    cik: "string"
    ein: "string"
    lei: "string"
    name: "string"
    ceo: "string"
    description: "string"
    foundedOn: "date"
    website: "string"
    businessAddress:
      street1: "string"
      street2: "string"
      city: "string"
      stateOrCountry: "string"
      zipCode: "string"
      isForeignLocation: "string"
      foreignStateTerritory: "string"
      country: "string"
      countryCode: "string"
      from: "date"
      to: "date"
    formerAddresses[]:
      street1: "string"
      street2: "string"
      city: "string"
      stateOrCountry: "string"
      zipCode: "string"
      isForeignLocation: "string"
      foreignStateTerritory: "string"
      country: "string"
      countryCode: "string"
      from: "date"
      to: "date"
    formerNames[]:
      name: "string"
      from: "date"
      to: "date"
    formerCeos[]:
      name: "string"
      from: "date"
      to: "date"
    sectors[]:
      name: "string"
      code: "string"
      system: "SIC | NAICS"
      from: "date"
      to: "date"
    shareholders[]:
      name: "string"
      code: "string"
    debts[]:
    




